# Generated by Django 6.0.5 on 2026-06-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
        ('users', '0002_user_organization_alter_user_role'),
    ]

    operations = [
    ]
