# Generated by Django 6.0.5 on 2026-06-03 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory'),
        ('products', '0004_delete_stockhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='low_stock_alert',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='change_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='new_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='previous_stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['variant'], name='inventory_s_variant_f9d072_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['created_at'], name='inventory_s_created_0e2add_idx'),
        ),
    ]
