# Generated by Django 6.0.3 on 2026-03-18 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('ADD', 'Add Stock'), ('REMOVE', 'Remove Stock'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUST', 'Manual Adjust')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('PCS', 'Piece'), ('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Liter'), ('BOX', 'Box'), ('PACK', 'Pack')], max_length=10)),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='products.productvariant')),
            ],
        ),
    ]
