# Generated by Django 6.0.3 on 2026-03-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_gender_stockhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
    ]
