# Generated by Django 6.0.3 on 2026-03-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productvariant_stock_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
